---
kind: pipeline
type: docker
name: deploy

# push 代码的时候就触发这个流水线
trigger:
  event:
    - push

# 定义缓存目录(放到宿主机的 /tmp/drone_cache 目录下)
volumes:
  - name: cache
    host:
      path: /tmp/drone_cache
  - name: deploy_target
    host:
      path: /root/gitea/study_notes

steps:
  # 使用缓存(如果有的话)
  - name: restore-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  # 安装依赖 编译源码 压缩打包
  - name: build-and-compress-source-code
    image: node:18
    pull: if-not-exists
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile
      - pnpm docs:build
      - ls -al
      - rm -rf /deploy_target/dist
      - cp -r ./dist/ /deploy_target/
      - mv ./docs/.vitepress/dist ./dist
      - ls /deploy_target/
      - echo "===== build completed ====="

  # 制作缓存(需要指定缓存目录, 不要每次去下载 node_modules)
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      restore: false
      mount:
        - ./node_modules
