name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download codes
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: install pnpm
        uses: pnpm/action-setup@master

      - name: config github pages
        uses: actions/configure-pages@v3

      - name: install dependencies
        run: pnpm install

      - name: biuld with VitePress
        run: |
          pnpm docs:build
          touch docs/.vitepress/dist/.nojekyll

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/.vitepress/dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
