name: Deploy VitePress site to Github Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

# Build jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ### download source codes
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - uses: pnpm/action-setup@v2 # Uncomment this if you're using pnpm
      # - uses: oven-sh/setup-bun@v1 # Uncomment this if you're using Bun

      ### install node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm # or pnpm / yarn
      ### configure github pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      ### install project dependencies
      - name: Install dependencies
        run: pnpm install # or pnpm install / yarn install / bun install
      - name: Build with VitePress
        run: |
          pnpm build
          touch src/.vitepress/dist/.nojekyll

      ### upload to github pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: src/.vitepress/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
